# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

## Settings
inhibit_all_warnings!
use_frameworks!

abstract_target 'defaults' do

    # Networking
    pod 'Alamofire', '4.9.1' 
    pod 'SDWebImage'
    pod 'SVProgressHUD'
    pod 'SwiftyJSON', '5.0.0'
    pod 'Charts', '3.4.0'
    pod 'Realm', '4.4.1'
    pod 'RealmSwift', '4.4.1'

    target '911'
    target '911Tests'
    target '911UITests'
    target 'Sensory'
end


